sudo: required
dist: trusty
cache:
  apt: true

language: cpp

addons:
  sonarqube:
    organization: "j-rivero-github"
    token:
      secure: "fb38bd53856750774b192e661a3be684d5802ccf"

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COVERALLS=ON
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release COVERALLS=OFF
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug COVERALLS=OFF
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release COVERALLS=OFF
    - os: osx
      osx_image: beta-xcode6.3
      compiler: clang
      env: BUILD_TYPE=Debug COVERALLS=OFF
    - os: osx
      osx_image: beta-xcode6.3
      compiler: clang
      env: BUILD_TYPE=Release COVERALLS=OFF

install:
  # Install dependencies for FCL
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 'ci/install_linux.sh' ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 'ci/install_osx.sh'   ; fi

script:
  # Create build directory
  - mkdir build
  - cd build 

  # Configure
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DFCL_COVERALLS=$COVERALLS ..

  # Build
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner
  - if [ $COVERALLS = ON ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then make coveralls; fi

  # Run unit tests
  - make test

  # Make sure we can install and uninstall with no issues
  - sudo make -j4 install
  - sudo make -j4 uninstall

cache:
  directories:
    - '$HOME/.sonar/cache'
