sudo: required
dist: trusty
cache:
  apt: true

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug   COVERALLS=OFF FCL_USE_EIGEN=OFF
  - BUILD_TYPE=Release COVERALLS=OFF FCL_USE_EIGEN=OFF
  - BUILD_TYPE=Release COVERALLS=OFF FCL_USE_EIGEN=ON

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COVERALLS=ON FCL_USE_EIGEN=ON COVERALLS_REPO_TOKEN=PheK7dcpQFPXAUG0wTMVTnSVF349jEJGc
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - libboost-all-dev
      - libeigen3-dev

install:
  # Install dependencies for FCL
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 'ci/install_linux.sh' ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 'ci/install_osx.sh'   ; fi

script:
  # Create build directory
  - mkdir build
  - cd build 

  # Configure
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DFCL_COVERALLS=$COVERALLS -DFCL_USE_EIGEN=${FCL_USE_EIGEN} ..

  # Build
  - make -j4
  - if [ $COVERALLS = ON ]; then make coveralls; fi

  # Run unit tests
  - make test

  # Make sure we can install and uninstall with no issues
  - sudo make -j4 install
  - sudo make -j4 uninstall

